maliabsi/finalProject-group8

static/style.css
templates/index.html
templates/login.html
templates/sign-up.html

Started login and signup page

---

models.py

not sure how the user table got switched back. Using just the stytchid in the user table then querying rest of user data from stytch db

User Table Update

---

templates/about-us.html
templates/login.html
templates/sign-up.html

I started the about-us.html page

added about-us and updated existing web pages

---

templates/communities.html
templates/index.html
templates/login.html

Fixed the links in nav bar so that they redirect to the correct page

fixed links in nav bar

---

app.py

added app route for about us page

added app route for about us

---

app.py

linting for app.py

---

static/style.css
templates/communities.html

had to factor in if user is signed in or not. If not signed in, they cannot create community. Else, they can

restyled community page

---

static/style.css

fixed hover for sign in button on communities page

hover fixed

---

static/style.css

fixed mission statement

---

templates/login.html

added if statement to display logout if user is signed in and login if not

handle logout

---

static/style.css
templates/index.html

made for loop to display 3 communities, and formatted / fixed visit button

fixed visit button

---

templates/visit_community.html

no changes rlly

---

templates/aboutUs.html
templates/communities.html

fixed pic and added form to visit community

fixed picture

---

app.py

was returning vars outside of if block that were created in if block

fixed logic error in community fn

---

app.py
static/style.css
templates/index.html
templates/login.html

made logout button appear only when a user is logged in

fixed logout

---

static/style.css
templates/visit_community.html

styled visit_communitity heheheh

Tayo made some addtions, I think I like them

---

templates/communities.html
templates/index.html

Closed form in two spots so that the correct id would be passed.

fixed bug where the communities don't load correctly

---

stytch_tools.py

Stytch tools now loads dotenv file.

added load dotenv for stytch tools

---

static/style.css
templates/aboutUs.html
templates/communities.html
templates/index.html
templates/login.html
templates/user.html
templates/visit_community.html

deleted logout button and created link so that users can logout from dropdown menu

fixed logout button

---

static/comm_styles.css
templates/communities.html

created text areas for tagline and description inputs when creating a community

created larger text boxes

---

static/comm_styles.css
templates/communities.html

added optional text fields so that users can enter donation link if they choose when creating a community

Donation link

---

app.py
stytch_tools.py

Should work, but heroku needs to work to test

Email login

---

app.py
static/style.css
templates/aboutUs.html
templates/communities.html
templates/index.html
templates/login.html
templates/user.html
templates/visit_community.html

Added app route for profile page and linked 'Your Profile' in the navbar dropdown to profile page

fixed navbar

---

app.py

forgot about events

---

static/comm_styles.css
static/profile_style.css
templates/user.html

styled profile page, still need to add some things

added styling for profile

---

static/login_styles.css
templates/login.html

added styling to login with email

fixed email_login style

---

app.py
stytch_tools.py

took main out of stytch_tools and profile gives all correct vars

Profile backend complete

---

static/comm_styles.css
static/index_style.css
static/profile_style.css
templates/communities.html
templates/user.html

1. Styled profile page & made created communities, created events, followed communities, and events a user plans on attending visible
2. Made entering community_name, tagline, and description required when creating community

styled profile page

---

app.py
templates/user.html

Added delete button so that communities can be deleted by creator

added delete button for comms

---

templates/aboutUs.html
templates/communities.html
templates/index.html
templates/login.html
templates/signup.html
templates/user.html
templates/visit_community.html

made it required to be logged in before seeing profile page

navbar tweak

---

templates/aboutUs.html
templates/communities.html
templates/index.html
templates/login.html
templates/signup.html
templates/user.html
templates/visit_community.html

your profile is only visible / reachable from navbar if logged in

navbar fix

---

unit_tests.py

the final two tests are added and are successful

---

templates/communities.html
templates/edit_event.html
templates/user.html

edit event

---

static/profile_style.css
templates/user.html

fixed legend styling and spacing of events

fixed spacing issue on profile page

---

static/comm_styles.css
static/login_styles.css
templates/communities.html
templates/login.html

made description fully visible under active communities

fixed active comm spacing and styled flash message

---

templates/user.html

Displays comm name that event belongs to for "attending events" and "your events"

added comm name that event belongs to
